### ISSUE TITLE
UpdateChecker: IllegalStateException: check() has not been called

### ISSUE THREAD

**Issue by jhqwqmc** [TechnicJelle/BlueMapCustomSkinProvider#1]
[21:01:56 ERROR]: [BlueMap] BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.lang.IllegalStateException: check() has not been called
        at com.technicjelle.UpdateChecker.logUpdateMessage(UpdateChecker.java:89) ~[[B][网页地图-自定义皮肤]BlueMapCustomSkinProvider-1.3.jar:?]
        at com.technicjelle.bluemapcustomskinprovider.BlueMapCustomSkinProvider.lambda$new$1(BlueMapCustomSkinProvider.java:32) ~[[B][网页地图-自定义皮肤]BlueMapCustomSkinProvider-1.3.jar:?]
        at de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:211) ~[[B][网页地图]BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:175) ~[[B][网页地图]BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:351) ~[[B][网页地图]BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:112) ~[[B][网页地图]BlueMap-3.16-spigot.jar:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:148) ~[[B][网页地图]BlueMap-3.16-spigot.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TechnicJelle** [comment]
Thank you for reporting this issue!
A fix for this is almost done (courtesy of @TBlueF :smile: ), it just needs to be proofread!

**Comment by TechnicJelle** [comment]
Fixed with ce6c14df191745cef6b128f70c13c37b90ea5ee6! You can download it [here](https://github.com/TechnicJelle/BlueMapCustomSkinProvider/releases/v1.5)!
